// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw7vkKvPYmwHlaP01MLs43_Z2V2jZ28B4',
    appId: '1:1099349948676:android:bd706d0afafb9e9a533851',
    messagingSenderId: '1099349948676',
    projectId: 'q-taxi-c9463',
    databaseURL: 'https://q-taxi-c9463-default-rtdb.firebaseio.com',
    storageBucket: 'q-taxi-c9463.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdkBDoXggd_jSbL5QBWf7qcxD5uDNHWoA',
    appId: '1:1099349948676:ios:08959afadc4c137e533851',
    messagingSenderId: '1099349948676',
    projectId: 'q-taxi-c9463',
    databaseURL: 'https://q-taxi-c9463-default-rtdb.firebaseio.com',
    storageBucket: 'q-taxi-c9463.firebasestorage.app',
    iosBundleId: 'com.example.qTripUser',
  );
}
